### ISSUE TITLE
Bug: License text in README.MD

### ISSUE THREAD

**Issue by whalemare** [TechSquidTV/Shoutify#43]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

You say in readme.md that it's `MIT` License, but in [license file](https://github.com/TechSquidTV/Shoutify/blob/main/LICENSE) it's Apache 2.0

### Expected behavior

License in `readme` and in `license` equals

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by takanome-dev** [comment]
Nice catch @whalemare :clap: 
Can assign it to you if you want to take it

**Comment by imvedanshmehra** [comment]
It looks like this issue is already resolved. We should close this issue to avoid confusion among contributors.

**Comment by takanome-dev** [comment]
Hey @imvedanshmehra, I think it's not resolved yet :arrow_down: 

![Screenshot from 2023-01-28 07-19-22](https://user-images.githubusercontent.com/79809121/215252883-36de3bad-9184-40d4-8dd1-969ee07de2d6.png)

**Comment by imvedanshmehra** [comment]
Oh, my bad! @TAKANOME-DEV  can you please assign this issue to me I'll fix it quickly.
